PYTHON QUESTION
(Solve any 10 Question)


In [43]:
#1. Write a Python program using lambda to calculate the square of a number entered by the user.

sq=lambda a:a**2
a=int(input("enter a number : "))
print(f"The square of {a} is : ",sq(a))

enter a number : 2
The square of 2 is :  4


In [2]:
#2. Use map to double all the elements in the list: [1, 2, 3, 4, 5].
def double(x):
  return x*2
my_list=[1,2,3,4,5]
doubled=list(map(double,my_list))
print(doubled)

[2, 4, 6, 8, 10]


In [3]:
#3. Use filter to extract all even numbers from the list: [10, 15, 20, 25, 30].

def checkeven(x):
  if x%2==0:
    return True
  else:
    return False
my_list=[10, 15, 20, 25, 30]
even_list=list(filter(checkeven,my_list))
print(even_list)

[10, 20, 30]


In [5]:
#4. Write a one-liner lambda function to check if a given number is a palindrome.
num=int(input("enter a number : "))

pal=lambda a:"palindrome" if a==a[::-1] else "not palindrome"
print(pal(str(num)))

enter a number : 86
not palindrome


In [6]:
#5. Write a function that takes a variable number of arguments (*args) and returns their sum.
def sum(*arg):
  sum=0
  for i in arg:
    sum+=i
  return sum
print(sum(1,2,3,4,5))

15


In [10]:
#6 Write a function that uses **kwargs to accept a student’s details (name, age, and grade) and print them in a formatted string.
def stud(**kwargs):
  print(kwargs)
stud(name="ram",roll=1,branch="cse")

{'name': 'ram', 'roll': 1, 'branch': 'cse'}


In [11]:
#11. Write a program to calculate the sum of all numbers in a list: [5, 10, 15, 20] using a for loop.
my_list=[5, 10, 15, 20]
sum=0
for i in my_list:
  sum+=i

print(sum)


50


In [17]:
#10 . Write a program to print the first 10 natural numbers using a for loop.
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [12]:
#8. Create a base class Animal with a method speak that prints"I am an animal."Create a derived class Dog that overrides the speak method to print "I am a dog."
class animal:
  def speak(self):
    print("i am an animal")
class dog(animal):
  def speak(self):
    print("i am a dog")
d=dog()
d.speak()

i am a dog


In [15]:
#13 factorial using while loop
num=int(input("enter a number : "))
fact=1
i=1
while i<=num:
  fact=fact*i
  i+=1
print(fact)

enter a number : 4
24


In [16]:
#12 Write a Python program to print the multiplication table of a given number using a while loop
num=int(input("enter a number : "))
for i in range(1,11):
  print(f"{num} * {i} = {num*i}")

enter a number : 5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
#14. Write a Python program to check if a number entered by the user is even or odd.
num=int(input("enter a number : "))

if num%2==0:
  print("even")
else:
  print("odd")


In [19]:
#20. Write a Python program to count the number of vowels in a string entered by the user.
my_str=input("enter a string : ")
count=0
for i in my_str.upper():
  if i=='A' or i=='E' or i=='I' or i=='O' or i=='U':
    count+=1
print(count)


enter a string : lnss
0


NumPy Questions
(Solve any 10 Question)

In [24]:
#1.Create a NumPy array of zeros with shape (3, 4).
import numpy as np
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
#2.Create a NumPy array of ones with shape (2, 5).
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
#3.Create a NumPy matrix with the values from 1 to 10 using np.arange().
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
#4.Create a NumPy array with numbers from 0 to 1 (inclusive) with a step size of 0.1 using np.arange().
np.arange(0,(1+0.1),0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [21]:
#5. Create a NumPy array with 10 equally spaced values between 0 and 1 using np.linspace() with endpoint=False. #
import numpy as np
np.linspace(0,1,10,endpoint=False)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [27]:
#6.Write a NumPy program to compute the square root of each element in the array [1, 4, 9, 16].
num=np.array([1,4,9,16])
np.sqrt(num)

array([1., 2., 3., 4.])

In [41]:
#7. Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6]).
num=np.array([2,3,4,5,6])
np.sum(num)

20

In [31]:
#8. Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min().
num=np.array([1, 5, 9, 3, 6])
np.min(num)

1

In [32]:
#9.Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max().
np.max(num)

9

In [33]:
#10. Use np.ceil() to round the elements of the array np.array([1.2, 2.5, 3.7, 4.9]) to the nearest greater integer.
num=np.array([1.2, 2.5, 3.7, 4.9])
np.ceil(num)

array([2., 3., 4., 5.])

In [34]:
#11. Generate an array of 5 random integers between 10 and 50 using np.random.randint().
np.random.randint(10,50,5)
#syntax : np.random.randint(low,high,size)


array([33, 37, 38, 30, 25])